(() => {
  'use strict';
  const toast = document.getElementById('customerToast');
  const showToast = text => { if (!toast) return; toast.textContent = text; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 2200); };
  document.getElementById('locationButton')?.addEventListener('click', () => { document.getElementById('locationStatus').textContent = 'تم تحديد الموقع بنجاح (بيانات تجريبية)'; showToast('تم حفظ موقعك التجريبي'); });
  document.getElementById('customerLogout')?.addEventListener('click', () => showToast('تم تسجيل الخروج من الوضع التجريبي'));
  const products = [{id:1,name:'ابرافنت اس ايروسول 200 جرعة',code:'20690',company:'تاج',category:'أدوية',price:29.88,discount:28,stock:18},{id:2,name:'ابرتيف 120 مللى شراب',code:'25173',company:'النيل',category:'أدوية',price:36,discount:28,stock:24},{id:3,name:'ابليفاى 10مجم اقراص',code:'19902',company:'فارما كير',category:'أدوية',price:127.08,discount:28,stock:0},{id:4,name:'فيتامين د3 1000 وحدة',code:'18420',company:'النيل',category:'مكملات',price:88.5,discount:15,stock:42},{id:5,name:'كريم ترطيب يومي 50 جم',code:'22810',company:'فارما كير',category:'عناية',price:64.9,discount:20,stock:12},{id:6,name:'ابريزين 5مجم شراب',code:'19257',company:'تاج',category:'أدوية',price:7.35,discount:30,stock:31}];
  let cart = JSON.parse(localStorage.getItem('orgaDemoCart') || '{}');
  const renderCart = () => { const target = document.getElementById('cartItems'); if (!target) return; const entries = Object.entries(cart).filter(([,q]) => q > 0); const total = entries.reduce((sum,[id,q]) => sum + products.find(p => p.id === Number(id)).price * q, 0); document.getElementById('cartCount').textContent = entries.reduce((sum,[,q]) => sum + q, 0); document.getElementById('cartTotal').textContent = `${total.toFixed(2)} ج.م`; target.innerHTML = entries.length ? entries.map(([id,q]) => { const p = products.find(item => item.id === Number(id)); return `<div class="cart-line"><div><b>${p.name}</b><small>${q} × ${p.price.toFixed(2)} ج.م</small></div><button data-remove="${p.id}">×</button></div>`; }).join('') : '<p class="empty-cart">السلة فارغة، اختر منتجًا للبدء.</p>'; target.querySelectorAll('[data-remove]').forEach(b => b.addEventListener('click', () => { delete cart[b.dataset.remove]; persist(); })); };
  const persist = () => { localStorage.setItem('orgaDemoCart', JSON.stringify(cart)); renderCart(); };
  const renderProducts = () => { const grid = document.getElementById('productsGrid'); if (!grid) return; const query = (document.getElementById('productSearch').value || '').toLowerCase(); const company = document.getElementById('companyFilter').value; const category = document.getElementById('categoryFilter').value; const list = products.filter(p => (!query || `${p.name} ${p.code}`.toLowerCase().includes(query)) && (!company || p.company === company) && (!category || p.category === category)); grid.innerHTML = list.map(p => `<article class="product-card ${p.stock ? '' : 'out'}"><h3>${p.name}</h3><span class="product-code">كود: ${p.code}</span><span class="product-company">${p.company} · ${p.category}</span><div class="product-price"><strong>${p.price.toFixed(2)} ج.م</strong><span>خصم ${p.discount}%</span></div><button data-add="${p.id}" ${p.stock ? '' : 'disabled'}>${p.stock ? 'إضافة للسلة' : 'غير متوفر'}</button></article>`).join('') || '<p class="empty-cart">لا توجد منتجات مطابقة للبحث.</p>'; grid.querySelectorAll('[data-add]').forEach(b => b.addEventListener('click', () => { cart[b.dataset.add] = (cart[b.dataset.add] || 0) + 1; persist(); showToast('تمت إضافة المنتج للسلة'); })); };
  document.querySelectorAll('#productSearch,#companyFilter,#categoryFilter').forEach(el => el.addEventListener('input', renderProducts));
  const panel = document.getElementById('cartPanel'); document.getElementById('cartButton')?.addEventListener('click', () => panel.classList.add('open')); document.getElementById('closeCart')?.addEventListener('click', () => panel.classList.remove('open')); document.getElementById('submitOrder')?.addEventListener('click', () => { if (!Object.keys(cart).length) return showToast('أضف منتجًا واحدًا على الأقل'); cart = {}; persist(); showToast('تم إرسال الطلب للمراجعة تجريبيًا'); }); renderProducts(); renderCart();
})();
