(() => {
'use strict';
const products=[
{id:1,name:'ابرافنت اس ايروسول 200 جرعة',company:'تاج',category:'أدوية',price:29.88,old:41.5,discount:28,stock:18,color:'blue'},
{id:2,name:'ابرتيف 120 مللى شراب',company:'النيل',category:'أدوية',price:36,old:50,discount:28,stock:24,color:'green'},
{id:3,name:'ابليفاى 10مجم اقراص',company:'فارما كير',category:'أدوية',price:127.08,old:176.5,discount:28,stock:0,color:'pink'},
{id:4,name:'فيتامين د3 1000 وحدة',company:'النيل',category:'مكملات',price:88.5,old:104,discount:15,stock:42,color:'amber'},
{id:5,name:'كريم ترطيب يومي 50 جم',company:'فارما كير',category:'عناية',price:64.9,old:81,discount:20,stock:12,color:'purple'},
{id:6,name:'ابريزين 5مجم شراب',company:'تاج',category:'أدوية',price:7.35,old:10.5,discount:30,stock:31,color:'teal'}];
let cart=JSON.parse(localStorage.getItem('orgaStoreCart')||'{}');
const $=s=>document.querySelector(s);const notify=msg=>{const n=$('#toast');n.textContent=msg;n.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>n.classList.remove('show'),2100)};const save=()=>{localStorage.setItem('orgaStoreCart',JSON.stringify(cart));renderCart()};
const filtered=()=>{const q=$('#searchInput').value.trim().toLowerCase(),company=$('#companyFilter').value,category=document.querySelector('.categories .active')?.dataset.category||'',max=Number($('#priceFilter').value),only=$('#availableOnly').checked,sort=$('#sortSelect').value;const list=products.filter(p=>(!q||`${p.name} ${p.company}`.toLowerCase().includes(q))&&(!company||p.company===company)&&(!category||p.category===category)&&p.price<=max&&(!only||p.stock>0));return list.sort((a,b)=>sort==='price'?a.price-b.price:sort==='discount'?b.discount-a.discount:a.id-b.id)};
function renderProducts(){const list=filtered();$('#resultsCount').textContent=`${list.length} منتجات`;$('#emptyState').hidden=Boolean(list.length);$('#productGrid').innerHTML=list.map(p=>`<article class="product-card"><div class="visual ${p.color}"><span class="pack">✚<small>ORGA</small></span><span class="discount">-${p.discount}%</span></div><h3>${p.name}</h3><span class="meta">${p.company} · ${p.category}</span><div class="bottom"><div class="price"><strong>${p.price.toFixed(2)} ج.م</strong><del>${p.old.toFixed(2)}</del></div><button class="add" data-add="${p.id}" ${p.stock?'':'disabled'}>${p.stock?'+ أضف للسلة':'غير متاح'}</button></div></article>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>{cart[b.dataset.add]=(cart[b.dataset.add]||0)+1;save();notify('أضيف المنتج إلى السلة')}))}
function renderCart(){const entries=Object.entries(cart).filter(([,q])=>q>0),count=entries.reduce((s,[,q])=>s+q,0),total=entries.reduce((s,[id,q])=>s+products.find(p=>p.id===Number(id)).price*q,0);$('#cartBadge').textContent=count;$('#subtotal').textContent=`${total.toFixed(2)} ج.م`;$('#drawerItems').innerHTML=entries.length?entries.map(([id,q])=>{const p=products.find(item=>item.id===Number(id));return `<div class="line"><span class="thumb">✚</span><div><b>${p.name}</b><small>${p.price.toFixed(2)} ج.م</small><div class="qty"><button data-minus="${p.id}">−</button><span>${q}</span><button data-plus="${p.id}">＋</button></div></div><strong>${(p.price*q).toFixed(2)}</strong></div>`}).join(''):'<div class="empty-drawer">السلة فارغة.<br>أضف منتجاتك لتبدأ الطلب.</div>';document.querySelectorAll('[data-minus]').forEach(b=>b.addEventListener('click',()=>change(b.dataset.minus,-1)));document.querySelectorAll('[data-plus]').forEach(b=>b.addEventListener('click',()=>change(b.dataset.plus,1)))}
function change(id,amount){cart[id]=(cart[id]||0)+amount;if(cart[id]<=0)delete cart[id];save()}
const drawer=$('#drawer');const openCart=()=>{drawer.classList.add('open');$('#overlay').style.display='block'};const closeCart=()=>{drawer.classList.remove('open');$('#overlay').style.display='none'};$('#cartTrigger').addEventListener('click',openCart);$('#closeCart').addEventListener('click',closeCart);$('#overlay').addEventListener('click',closeCart);$('#checkout').addEventListener('click',async()=>{const entries=Object.entries(cart).filter(([,quantity])=>quantity>0);if(!entries.length)return notify('أضف منتجًا واحدًا على الأقل');const total=entries.reduce((sum,[id,quantity])=>sum+products.find(product=>product.id===Number(id)).price*quantity,0);try{const response=await fetch('http://localhost:4310/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerId:140,items:entries.map(([id,quantity])=>({productId:Number(id),quantity})),total})});if(!response.ok)throw new Error('order_failed');const result=await response.json();cart={};save();closeCart();notify(`تم إرسال الطلب رقم ${result.data.id}`)}catch(error){notify('تعذر إرسال الطلب، تأكد من تشغيل API المحلي')}});$('#repeatOrder').addEventListener('click',()=>notify('لا يوجد طلب سابق في النسخة التجريبية'));$('#ordersButton').addEventListener('click',()=>notify('ستظهر طلباتك هنا بعد أول عملية شراء'));$('#accountButton').addEventListener('click',()=>notify('صفحة الحساب قيد التجهيز'));$('#shopNow').addEventListener('click',()=>$('#productsSection').scrollIntoView());
document.querySelectorAll('.categories button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.categories button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts()}));$('#searchInput').addEventListener('input',renderProducts);$('#companyFilter').addEventListener('change',renderProducts);$('#availableOnly').addEventListener('change',renderProducts);$('#sortSelect').addEventListener('change',renderProducts);$('#priceFilter').addEventListener('input',e=>{$('#priceValue').textContent=e.target.value;renderProducts()});$('#clearFilters').addEventListener('click',()=>{$('#companyFilter').value='';$('#priceFilter').value=150;$('#priceValue').textContent=150;$('#availableOnly').checked=false;renderProducts()});$('#filterButton').addEventListener('click',()=>$('#filters').classList.toggle('open'));renderProducts();renderCart();
})();
